### ISSUE TITLE
Cannot update webhook configurations

### ISSUE THREAD

**Issue by marzianor9** [gatekeeper/gatekeeper-operator#139]
whenever i try to change the webhook configurations, i get this error:
"level":"error","ts":1614165913.2016525,"logger":"cert-rotation","msg":"secret is not well-formed, cannot update webhook configurations","error":"Cert secret is not well-formed, missing ca.crt"

**Comment by marzianor9** [comment]
This is the configuration i tried to apply:

apiVersion: operator.gatekeeper.sh/v1alpha1
kind: Gatekeeper
metadata:
  name: gatekeeper
spec:
  # Add fields here
  audit:
    replicas: 1
    logLevel: ERROR
  mutatingWebhook: "Enabled"
  webhook:
    failurePolicy: "Ignore"
    namespaceSelector:
      matchLabels:
        "mutate": "enabled"

**Comment by font** [comment]
Are you able to provide steps to reproduce this? That error does not look specific to the operator, but to the gatekeeper controller manager that has a built-in cert rotation mechanism. It's indicating the secret is not well formed and seems unrelated to the webhook. Take a look at the `gatekeeper-webhook-server-cert` secret and make sure it has a `ca.crt` key in the data field.

**Comment by font** [comment]
@marzianor9 Is this still an issue?

**Comment by marzianor9** [comment]
no, it was solved
