### ISSUE TITLE
Add CI testing

### ISSUE THREAD

**Issue by font** [gatekeeper/gatekeeper-operator#2]
This issue captures the work needed to implement some level of CI testing using for example GitHub Actions. The CI tests would ideally run:
- [x] unit tests
- [x] e2e tests to verify successful operation of the operator e.g. successfully installs Gatekeeper

The CI testing would execute upon the creation or updating of PRs as well as any merges.

**Comment by tchughesiv** [comment]
@font openshift CI system ok? did you have something else in mind?
