### ISSUE TITLE
Add support for installing Gatekeeper on OpenShift

### ISSUE THREAD

**Issue by font** [gatekeeper/gatekeeper-operator#26]
The main differences to get Gatekeeper installed on OCP are around the Security Context Constraints and the seccomp profile annotations. See https://github.com/open-policy-agent/gatekeeper#running-on-openshift-4x for reference as well as https://github.com/redhat-cop/rego-policies/blob/b14ce1f9ec08e5eede257f0ecc5525a58cbb3a48/_test/deploy-gatekeeper.sh#L24-L58 for an older example.

Additionally, we would want to have a framework for supporting installing Gatekeeper on any Kubernetes distribution, OCP being one of them.

**Comment by willkutler** [comment]
FYI @font - going to take a look at the install PR to try and investigate how much needs to be done for this

**Comment by font** [comment]
Fixed by #44.
