### ISSUE TITLE
Support defaulting for Gatekeeper Operator CRD

### ISSUE THREAD

**Issue by font** [gatekeeper/gatekeeper-operator#5]
The Gatekeeper Operator will support some level of defaulting for various omitted fields that are not required in the Gatekeeper CRD. The list of fields that are optional are captured in the CRD API. The defaulting behavior will be done by either:
1. As part of CRD defaulting markers when defining the Go struct https://book.kubebuilder.io/reference/markers/crd-validation.html.
2. As part of an Operator mutating admission webhook that is deployed as part of the Operator.

It's preferred to use option 1 wherever possible.

**Comment by JAORMX** [comment]
@font right, option one is preferable. It sure makes life easier :smile:

**Comment by font** [comment]
There is another option here that we are currently relying on, and that is defaulting based on the Gatekeeper manifests that are compiled into the operator. So if the user provides a completely empty Gatekeeper CR, the defaulting that occurs is to use whatever the Gatekeeper manifests specify as the default. Those should be good enough sane defaults. So I think this is a good enough defaulting strategy for now and we can revisit this later if it proves to be insufficient in the future.
