### ISSUE TITLE
Convert operator and its custom resource to be cluster-scoped instead of namespace-scoped

### ISSUE THREAD

**Issue by font** [gatekeeper/gatekeeper-operator#70]

**Comment by ruromero** [comment]
Do we want that?
The operator should be namespace-scoped but only be able to be installed in one namespace. Then we should create one single gatekeeper configuration.
The instantiated gatekeeper cluster should watch all namespaces for gatekeeper-related resources (templates and constraints) and create the necessary admissionWebhooks.
